# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce0ebb3738cae442bbc047062c9e3087f60b98fc5f169d52898b25f2145e1301a603d78702a375d88fa935fd5338dc6602e847cfd8a466ae22d293bdefccec32

test:
  secret_key_base: 017d350a7c66e9c6d26e11f6714b128be33eddf199643ece12068385c4234c51eadcf29c1b2e4b914a56c97efee5bb37a6a3ae03f62cc9008c49c660e116d6c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
